# Generated by Django 5.0.4 on 2024-05-04 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timestamp_search', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chat',
            old_name='last_chat_id',
            new_name='last_conversation_id',
        ),
    ]
