# Generated by Django 5.0.4 on 2024-05-04 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timestamp_search', '0002_rename_last_chat_id_chat_last_conversation_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conversation',
            name='video_id',
        ),
        migrations.RemoveField(
            model_name='conversation',
            name='video_title',
        ),
        migrations.AddField(
            model_name='timestamp',
            name='video_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='timestamp',
            name='video_title',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
