# Generated by Django 5.0.4 on 2024-05-04 12:37

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timestamp_search', '0003_remove_conversation_video_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timestamp',
            name='conversation',
        ),
        migrations.RemoveField(
            model_name='timestamp',
            name='video_id',
        ),
        migrations.RemoveField(
            model_name='timestamp',
            name='video_title',
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('video_title', models.CharField(blank=True, max_length=1000, null=True)),
                ('video_id', models.CharField(blank=True, max_length=100, null=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='timestamp_search.conversation')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='timestamp',
            name='video',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='time_stamps', to='timestamp_search.video'),
            preserve_default=False,
        ),
    ]
