# Generated by Django 5.0.4 on 2024-05-04 18:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timestamp_search', '0004_remove_timestamp_conversation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='created_at',
            field=models.DateTimeField(auto_created=True, default=datetime.datetime(2024, 5, 4, 18, 0, 50, 294942, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
