# Generated by Django 5.0.4 on 2024-05-04 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timestamp_search', '0005_conversation_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversation',
            name='created_at',
            field=models.DateTimeField(auto_created=True, auto_now=True),
        ),
    ]
