# Generated by Django 5.0.4 on 2024-05-04 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timestamp_search', '0006_alter_conversation_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='chat_title',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
